[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 144000
    UnBondPeriodInEpochs = 10
    MinStepValue = "100000000000000000000"
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 2169
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = true
    StakeLimitPercentage = 1.0 #fraction of value 1 - 100%, for the time being no stake limit
    NodeLimitPercentage = 0.03125 #fraction of value 0.1 - 10% (1600*0.03125=50)

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1ze6pgefwc7mdx0rhje3h50kkgt26ut3gx8ytezndkz8fjcf96gsqsd7ugw"

[GovernanceSystemSCConfig]
    OwnerAddress = "erd1qqqqqqqqqqqqqpgq0gq09608js3gje72v0yzc56k6glc852gl94sgtahk2"
    [GovernanceSystemSCConfig.V1]
        NumNodes           = 500
        ProposalCost       = "5000000000000000000" #5 eGLD
        MinQuorum          = 400
        MinPassThreshold   = 300
        MinVetoThreshold   = 50
    [GovernanceSystemSCConfig.Active]
        ProposalCost       = "1000000000000000000000" #1000 eGLD
        LostProposalFee    = "10000000000000000000"   #10 eGLD
        MinQuorum          = 0.2  #fraction of value 0.2  - 20%
        MinPassThreshold   = 0.5  #fraction of value 0.5  - 50%
        MinVetoThreshold   = 0.33 #fraction of value 0.33 - 33%

[DelegationManagerSystemSCConfig]
    MinCreationDeposit = "1250000000000000000000" #1.25K eGLD
    MinStakeAmount = "1000000000000000000" #1 eGLD
    ConfigChangeAddress = "erd1qqqqqqqqqqqqqpgq0gq09608js3gje72v0yzc56k6glc852gl94sgtahk2"

[DelegationSystemSCConfig]
    MinServiceFee  = 0
    MaxServiceFee  = 10000

# Changing this config is not backwards compatible
[SoftAuctionConfig]
    TopUpStep = "10000000000000000000" # 10 EGLD
    MinTopUp = "1000000000000000000" # 1 EGLD should be minimum
    MaxTopUp = "32000000000000000000000000" # 32 mil EGLD
    MaxNumberOfIterations = 100000 # 100k max number of iterations for soft auction config
